app_country:
    resource: "@AppBundle/Resources/config/routing/country.yml"
    prefix:   /country

app_category:
    prefix: /category
    resource: "@AppBundle/Resources/config/routing/category.yml"
app_product:
    prefix: /product
    resource: "@AppBundle/Resources/config/routing/product.yml"
